SALT="23;5l1n345;;asdf23581g3bsadfkggb'aq3;asdbbzm.aaMEF201J1;ASDFN386972158804885504"

THUMBNAIL_LIT_WIDTH = 300
THUMBNAIL_MID_WIDTH = 800

STATUS_NORMAL = 1
STATUS_DELETE = 0

ROLE_ADMIN = 'ADMIN'
ROLE_AUTHOR = 'AUTHOR'
ROLE_DEFAULT = 'DEFAULT'


ORI_MINIMOGRAPHY = "minimography"
ORI_UNSPLASH = "unsplash"

COIN_DIRECTION_DEBIT = 'DEBIT'
COIN_DIRECTION_CREDIT = 'CREDIT'

COIN_REASON_ADDTAG = u'新建标签'
COIN_REASON_NEWREG = u'注册新用户'
COIN_REASON_DOWNLOAD = u'下载高清大图'
